baseURL = 'https://example.org/'
title = 'My New Hugo Site'
languageCode = 'en-gb'
theme = 'liffstyle'
timezone = 'Europe/London'
[taxonomies]
category = 'categories'
tag = 'tags'
strand = 'strand'
year = 'year'
