baseURL = 'https://example.org/'
title = 'LIFF Archive'
languageCode = 'en-gb'
theme = 'liffstyle'
timezone = 'Europe/London'

[frontmatter]
date = [':filename', 'date']

[taxonomies]
category = 'categories'
tag = 'tags'
strand = 'strand'
year = 'year'
