baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'My New Hugo Site'

[menus]

[[menus.main]]
name = 'By Year'
pageRef = '/films'
weight = 20

[[menus.main]]
name = 'By Strand'
pageRef = '/strand'
weight = 30

[[menus.main]]
name = 'By Title'
pageRef = '/all'
weight = 30
[module]
[module.hugoVersion]
extended = false
min = '0.146.0'
